/**
 * PurchaseOrderServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';


const APIException = require('./APIException');
/**
 * Creates an instance of OrderNotFoundFaultException
 */
class OrderNotFoundFaultException extends APIException {
    /**
     * @constructor
     */
    constructor() {
        super();
        /**
         * TODO: Write general description for this field
         */
        this.parameters = null;
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'parameters', realName: 'parameters', type: 'OrderNotFoundFaultType' },
        ]);
    }
}

module.exports = OrderNotFoundFaultException;
