/**
 * NewAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of PaymentData
 */
class PaymentData extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.name = this.constructor.getValue(obj.name);
        this.cardNumber = this.constructor.getValue(obj.cardNumber || obj['card number']);
        this.cvvNumber = this.constructor.getValue(obj.cvvNumber || obj['cvv number']);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'name', realName: 'name' },
            { name: 'cardNumber', realName: 'card number' },
            { name: 'cvvNumber', realName: 'cvv number' },
        ]);
    }
}

module.exports = PaymentData;
