/**
 * PurchaseOrderServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const PurchaseOrderType = require('../lib/Models/PurchaseOrderType');
const OrderConfirmationType = require('../lib/Models/OrderConfirmationType');
const GetOrderStatusType = require('../lib/Models/GetOrderStatusType');
const GetOrderStatusResponseType = require('../lib/Models/GetOrderStatusResponseType');
const OrderNotFoundFaultType = require('../lib/Models/OrderNotFoundFaultType');
const OrderConfirmation = require('../lib/Models/OrderConfirmation');
const GetOrderStatusResponse = require('../lib/Models/GetOrderStatusResponse');
const PurchaseOrder = require('../lib/Models/PurchaseOrder');
const GetOrderStatus = require('../lib/Models/GetOrderStatus');
const OAuthToken = require('../lib/Models/OAuthToken');
const OrderNotFoundFaultException = require('../lib/Exceptions/OrderNotFoundFaultException');
const OAuthProviderException = require('../lib/Exceptions/OAuthProviderException');

const classMap = {
    PurchaseOrderType,
    OrderConfirmationType,
    GetOrderStatusType,
    GetOrderStatusResponseType,
    OrderNotFoundFaultType,
    OrderConfirmation,
    GetOrderStatusResponse,
    PurchaseOrder,
    GetOrderStatus,
    OAuthToken,
    OrderNotFoundFaultException,
    OAuthProviderException,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
